--HEAD: RECEBE UMA LISTA E RETORNA A CABEÇA DELA
head [5,4,3,2,1]
--TAIL: RECEBE UMA LISTA E RETORNA A SUA CAUDA
tail [5,4,3,2,1]
--LAST: RECEBE UMA LISTA E RETORA SEU ÚLTIMO ELEMENTO.
last [5,4,3,2,1]
--INIT: RECEBE UMA LISTA E RETORNA TUDO COM EXCEÇÃODO ÚLTIMO ELEMENTO
init [5,4,3,2,1]
